import type { ConstructionMethod } from '../domain/types/method';

/**
 * Catálogo de métodos construtivos. Para adicionar um novo método, basta
 * adicionar um novo objeto aqui e as chaves de tradução correspondentes em
 * `src/i18n/{idioma}/methods.json` — nenhuma outra parte do sistema precisa mudar
 * (comparador, calculadoras e telas de detalhe leem deste array).
 */
export const constructionMethods: ConstructionMethod[] = [
  {
    id: 'conventional-masonry',
    nameKey: 'methods.conventionalMasonry.name',
    descriptionKey: 'methods.conventionalMasonry.description',
    prosKeys: [
      'methods.conventionalMasonry.pros.0',
      'methods.conventionalMasonry.pros.1',
      'methods.conventionalMasonry.pros.2',
    ],
    consKeys: [
      'methods.conventionalMasonry.cons.0',
      'methods.conventionalMasonry.cons.1',
    ],
    speed: 2,
    difficulty: 3,
    durability: 5,
    maintenance: 2,
    wasteLevel: 4,
    skillRequired: 3,
    relativeCostFactor: 1.0,
    materialIds: ['ceramic-block-9x19x39', 'ready-concrete-m3', 'rebar-10mm-12m'],
    toolIds: ['trowel', 'level', 'concreteMixer'],
  },
  {
    id: 'structural-block',
    nameKey: 'methods.structuralBlock.name',
    descriptionKey: 'methods.structuralBlock.description',
    prosKeys: ['methods.structuralBlock.pros.0', 'methods.structuralBlock.pros.1'],
    consKeys: ['methods.structuralBlock.cons.0', 'methods.structuralBlock.cons.1'],
    speed: 3,
    difficulty: 3,
    durability: 5,
    maintenance: 2,
    wasteLevel: 3,
    skillRequired: 3,
    relativeCostFactor: 0.92,
    materialIds: ['concrete-block-14x19x39', 'rebar-10mm-12m'],
    toolIds: ['trowel', 'level'],
  },
  {
    id: 'ceramic-brick',
    nameKey: 'methods.ceramicBrick.name',
    descriptionKey: 'methods.ceramicBrick.description',
    prosKeys: ['methods.ceramicBrick.pros.0', 'methods.ceramicBrick.pros.1'],
    consKeys: ['methods.ceramicBrick.cons.0'],
    speed: 2,
    difficulty: 2,
    durability: 5,
    maintenance: 2,
    wasteLevel: 4,
    skillRequired: 2,
    relativeCostFactor: 0.95,
    materialIds: ['ceramic-block-9x19x39'],
    toolIds: ['trowel', 'level'],
  },
  {
    id: 'concrete-block',
    nameKey: 'methods.concreteBlock.name',
    descriptionKey: 'methods.concreteBlock.description',
    prosKeys: ['methods.concreteBlock.pros.0', 'methods.concreteBlock.pros.1'],
    consKeys: ['methods.concreteBlock.cons.0'],
    speed: 3,
    difficulty: 2,
    durability: 5,
    maintenance: 2,
    wasteLevel: 3,
    skillRequired: 2,
    relativeCostFactor: 0.9,
    materialIds: ['concrete-block-14x19x39'],
    toolIds: ['trowel', 'level'],
  },
  {
    id: 'eco-brick',
    nameKey: 'methods.ecoBrick.name',
    descriptionKey: 'methods.ecoBrick.description',
    prosKeys: [
      'methods.ecoBrick.pros.0',
      'methods.ecoBrick.pros.1',
      'methods.ecoBrick.pros.2',
    ],
    consKeys: ['methods.ecoBrick.cons.0'],
    speed: 4,
    difficulty: 2,
    durability: 4,
    maintenance: 2,
    wasteLevel: 1,
    skillRequired: 2,
    relativeCostFactor: 0.85,
    materialIds: ['eco-brick'],
    toolIds: ['level', 'rubberMallet'],
  },
  {
    id: 'reinforced-concrete',
    nameKey: 'methods.reinforcedConcrete.name',
    descriptionKey: 'methods.reinforcedConcrete.description',
    prosKeys: ['methods.reinforcedConcrete.pros.0', 'methods.reinforcedConcrete.pros.1'],
    consKeys: ['methods.reinforcedConcrete.cons.0', 'methods.reinforcedConcrete.cons.1'],
    speed: 2,
    difficulty: 5,
    durability: 5,
    maintenance: 2,
    wasteLevel: 3,
    skillRequired: 5,
    relativeCostFactor: 1.35,
    materialIds: ['ready-concrete-m3', 'rebar-10mm-12m', 'tie-wire-kg'],
    toolIds: ['formwork', 'vibrator', 'craneOrHoist'],
  },
  {
    id: 'steel-frame',
    nameKey: 'methods.steelFrame.name',
    descriptionKey: 'methods.steelFrame.description',
    prosKeys: [
      'methods.steelFrame.pros.0',
      'methods.steelFrame.pros.1',
      'methods.steelFrame.pros.2',
    ],
    consKeys: ['methods.steelFrame.cons.0', 'methods.steelFrame.cons.1'],
    speed: 5,
    difficulty: 4,
    durability: 4,
    maintenance: 3,
    wasteLevel: 1,
    skillRequired: 4,
    relativeCostFactor: 1.15,
    materialIds: [],
    toolIds: ['screwGun', 'level', 'laserLevel'],
  },
  {
    id: 'light-steel-frame',
    nameKey: 'methods.lightSteelFrame.name',
    descriptionKey: 'methods.lightSteelFrame.description',
    prosKeys: ['methods.lightSteelFrame.pros.0', 'methods.lightSteelFrame.pros.1'],
    consKeys: ['methods.lightSteelFrame.cons.0'],
    speed: 5,
    difficulty: 4,
    durability: 4,
    maintenance: 3,
    wasteLevel: 1,
    skillRequired: 4,
    relativeCostFactor: 1.1,
    materialIds: [],
    toolIds: ['screwGun', 'level'],
  },
  {
    id: 'wood-frame',
    nameKey: 'methods.woodFrame.name',
    descriptionKey: 'methods.woodFrame.description',
    prosKeys: ['methods.woodFrame.pros.0', 'methods.woodFrame.pros.1'],
    consKeys: ['methods.woodFrame.cons.0', 'methods.woodFrame.cons.1'],
    speed: 4,
    difficulty: 4,
    durability: 3,
    maintenance: 4,
    wasteLevel: 2,
    skillRequired: 4,
    relativeCostFactor: 1.05,
    materialIds: ['wood-joist-m'],
    toolIds: ['circularSaw', 'nailGun', 'level'],
  },
  {
    id: 'prefabricated',
    nameKey: 'methods.prefabricated.name',
    descriptionKey: 'methods.prefabricated.description',
    prosKeys: ['methods.prefabricated.pros.0', 'methods.prefabricated.pros.1'],
    consKeys: ['methods.prefabricated.cons.0', 'methods.prefabricated.cons.1'],
    speed: 5,
    difficulty: 2,
    durability: 3,
    maintenance: 3,
    wasteLevel: 1,
    skillRequired: 2,
    relativeCostFactor: 0.8,
    materialIds: [],
    toolIds: ['craneOrHoist'],
  },
];

export function findConstructionMethod(id: string): ConstructionMethod | undefined {
  return constructionMethods.find((m) => m.id === id);
}
