import type { StageDefinition } from '../domain/types/stage';

function steps(stageId: string, count: number): string[] {
  return Array.from({ length: count }, (_, i) => `guides.${stageId}.steps.${i}`);
}
function mistakes(stageId: string, count: number): string[] {
  return Array.from({ length: count }, (_, i) => `guides.${stageId}.mistakes.${i}`);
}
function tips(stageId: string, count: number): string[] {
  return Array.from({ length: count }, (_, i) => `guides.${stageId}.tips.${i}`);
}
function checklist(stageId: string, count: number): string[] {
  return Array.from({ length: count }, (_, i) => `guides.${stageId}.checklist.${i}`);
}

/**
 * As 30 etapas padrão de uma obra (briefing §10). `contentComplete: true`
 * indica que o guia passo a passo foi escrito em profundidade nesta V1
 * (ver docs/ROADMAP.md). As demais têm estrutura e metadados completos, com
 * um roteiro-base pronto para expansão pela comunidade (ver README, "Como
 * contribuir").
 */
export const stageDefinitions: StageDefinition[] = [
  {
    id: 'planning',
    order: 1,
    nameKey: 'stages.planning.name',
    categoryKey: 'stages.categories.preparation',
    objectiveKey: 'guides.planning.objective',
    difficulty: 1,
    requiresProfessional: 'none',
    tools: {
      essentialKeys: ['tools.measuringTape', 'tools.notebook'],
      optionalKeys: ['tools.laserMeasure'],
      safetyKeys: [],
    },
    prerequisiteStageIds: [],
    stepKeys: steps('planning', 5),
    commonMistakeKeys: mistakes('planning', 3),
    tipKeys: tips('planning', 3),
    checklistItemKeys: checklist('planning', 4),
    relatedVideoIds: ['planning-basics'],
    contentComplete: true,
  },
  {
    id: 'design',
    order: 2,
    nameKey: 'stages.design.name',
    categoryKey: 'stages.categories.preparation',
    objectiveKey: 'guides.design.objective',
    difficulty: 2,
    requiresProfessional: 'recommended',
    tools: {
      essentialKeys: ['tools.measuringTape'],
      optionalKeys: ['tools.designSoftware'],
      safetyKeys: [],
    },
    prerequisiteStageIds: ['planning'],
    stepKeys: steps('design', 4),
    commonMistakeKeys: mistakes('design', 2),
    tipKeys: tips('design', 2),
    checklistItemKeys: checklist('design', 3),
    relatedVideoIds: [],
    contentComplete: false,
  },
  {
    id: 'site-work',
    order: 3,
    nameKey: 'stages.siteWork.name',
    categoryKey: 'stages.categories.preparation',
    objectiveKey: 'guides.siteWork.objective',
    difficulty: 3,
    requiresProfessional: 'recommended',
    tools: {
      essentialKeys: ['tools.shovel', 'tools.levelHose'],
      optionalKeys: ['tools.excavator'],
      safetyKeys: ['safety.boots', 'safety.gloves'],
    },
    prerequisiteStageIds: ['design'],
    stepKeys: steps('site-work', 4),
    commonMistakeKeys: mistakes('site-work', 2),
    tipKeys: tips('site-work', 2),
    checklistItemKeys: checklist('site-work', 3),
    relatedVideoIds: [],
    contentComplete: false,
  },
  {
    id: 'foundation',
    order: 4,
    nameKey: 'stages.foundation.name',
    categoryKey: 'stages.categories.structure',
    objectiveKey: 'guides.foundation.objective',
    difficulty: 5,
    requiresProfessional: 'required',
    tools: {
      essentialKeys: [
        'tools.shovel',
        'tools.levelHose',
        'tools.concreteMixer',
        'tools.wheelbarrow',
      ],
      optionalKeys: ['tools.vibrator'],
      safetyKeys: ['safety.boots', 'safety.gloves', 'safety.glasses'],
    },
    prerequisiteStageIds: ['site-work'],
    stepKeys: steps('foundation', 9),
    commonMistakeKeys: mistakes('foundation', 4),
    tipKeys: tips('foundation', 4),
    checklistItemKeys: checklist('foundation', 6),
    relatedVideoIds: ['foundation-basics'],
    contentComplete: true,
  },
  {
    id: 'structure',
    order: 5,
    nameKey: 'stages.structure.name',
    categoryKey: 'stages.categories.structure',
    objectiveKey: 'guides.structure.objective',
    difficulty: 5,
    requiresProfessional: 'required',
    tools: {
      essentialKeys: ['tools.formwork', 'tools.vibrator', 'tools.level'],
      optionalKeys: ['tools.craneOrHoist'],
      safetyKeys: ['safety.helmet', 'safety.harness'],
    },
    prerequisiteStageIds: ['foundation'],
    stepKeys: steps('structure', 4),
    commonMistakeKeys: mistakes('structure', 2),
    tipKeys: tips('structure', 2),
    checklistItemKeys: checklist('structure', 3),
    relatedVideoIds: [],
    contentComplete: false,
  },
  {
    id: 'masonry',
    order: 6,
    nameKey: 'stages.masonry.name',
    categoryKey: 'stages.categories.structure',
    objectiveKey: 'guides.masonry.objective',
    difficulty: 3,
    requiresProfessional: 'recommended',
    tools: {
      essentialKeys: [
        'tools.trowel',
        'tools.level',
        'tools.stringLine',
        'tools.rubberMallet',
      ],
      optionalKeys: ['tools.laserLevel'],
      safetyKeys: ['safety.gloves', 'safety.glasses'],
    },
    prerequisiteStageIds: ['structure'],
    stepKeys: steps('masonry', 8),
    commonMistakeKeys: mistakes('masonry', 4),
    tipKeys: tips('masonry', 3),
    checklistItemKeys: checklist('masonry', 5),
    relatedVideoIds: ['masonry-basics'],
    contentComplete: true,
  },
  {
    id: 'slabs',
    order: 7,
    nameKey: 'stages.slabs.name',
    categoryKey: 'stages.categories.structure',
    objectiveKey: 'guides.slabs.objective',
    difficulty: 5,
    requiresProfessional: 'required',
    tools: {
      essentialKeys: ['tools.formwork', 'tools.vibrator'],
      optionalKeys: ['tools.craneOrHoist'],
      safetyKeys: ['safety.helmet', 'safety.harness'],
    },
    prerequisiteStageIds: ['masonry'],
    stepKeys: steps('slabs', 4),
    commonMistakeKeys: mistakes('slabs', 2),
    tipKeys: tips('slabs', 2),
    checklistItemKeys: checklist('slabs', 3),
    relatedVideoIds: [],
    contentComplete: false,
  },
  {
    id: 'roofing',
    order: 8,
    nameKey: 'stages.roofing.name',
    categoryKey: 'stages.categories.envelope',
    objectiveKey: 'guides.roofing.objective',
    difficulty: 4,
    requiresProfessional: 'recommended',
    tools: {
      essentialKeys: ['tools.ladder', 'tools.screwGun', 'tools.level'],
      optionalKeys: ['tools.scaffold'],
      safetyKeys: ['safety.harness', 'safety.helmet'],
    },
    prerequisiteStageIds: ['slabs'],
    stepKeys: steps('roofing', 8),
    commonMistakeKeys: mistakes('roofing', 4),
    tipKeys: tips('roofing', 3),
    checklistItemKeys: checklist('roofing', 5),
    relatedVideoIds: ['roofing-basics'],
    contentComplete: true,
  },
  {
    id: 'waterproofing',
    order: 9,
    nameKey: 'stages.waterproofing.name',
    categoryKey: 'stages.categories.envelope',
    objectiveKey: 'guides.waterproofing.objective',
    difficulty: 3,
    requiresProfessional: 'recommended',
    tools: {
      essentialKeys: ['tools.brush', 'tools.trowel'],
      optionalKeys: [],
      safetyKeys: ['safety.gloves', 'safety.mask'],
    },
    prerequisiteStageIds: ['roofing'],
    stepKeys: steps('waterproofing', 4),
    commonMistakeKeys: mistakes('waterproofing', 3),
    tipKeys: tips('waterproofing', 2),
    checklistItemKeys: checklist('waterproofing', 3),
    relatedVideoIds: [],
    contentComplete: false,
  },
  {
    id: 'frames',
    order: 10,
    nameKey: 'stages.frames.name',
    categoryKey: 'stages.categories.envelope',
    objectiveKey: 'guides.frames.objective',
    difficulty: 3,
    requiresProfessional: 'none',
    tools: {
      essentialKeys: ['tools.level', 'tools.screwGun'],
      optionalKeys: [],
      safetyKeys: ['safety.gloves'],
    },
    prerequisiteStageIds: ['masonry'],
    stepKeys: steps('frames', 4),
    commonMistakeKeys: mistakes('frames', 2),
    tipKeys: tips('frames', 2),
    checklistItemKeys: checklist('frames', 3),
    relatedVideoIds: [],
    contentComplete: false,
  },
  {
    id: 'hydraulic',
    order: 11,
    nameKey: 'stages.hydraulic.name',
    categoryKey: 'stages.categories.installations',
    objectiveKey: 'guides.hydraulic.objective',
    difficulty: 4,
    requiresProfessional: 'recommended',
    tools: {
      essentialKeys: ['tools.pipeCutter', 'tools.pvcGlueBrush', 'tools.level'],
      optionalKeys: ['tools.threadingTool'],
      safetyKeys: ['safety.gloves', 'safety.glasses'],
    },
    prerequisiteStageIds: ['masonry'],
    stepKeys: steps('hydraulic', 8),
    commonMistakeKeys: mistakes('hydraulic', 4),
    tipKeys: tips('hydraulic', 3),
    checklistItemKeys: checklist('hydraulic', 5),
    relatedVideoIds: ['hydraulic-basics'],
    contentComplete: true,
  },
  {
    id: 'sanitary',
    order: 12,
    nameKey: 'stages.sanitary.name',
    categoryKey: 'stages.categories.installations',
    objectiveKey: 'guides.sanitary.objective',
    difficulty: 4,
    requiresProfessional: 'recommended',
    tools: {
      essentialKeys: ['tools.pipeCutter', 'tools.level'],
      optionalKeys: [],
      safetyKeys: ['safety.gloves', 'safety.mask'],
    },
    prerequisiteStageIds: ['masonry'],
    stepKeys: steps('sanitary', 4),
    commonMistakeKeys: mistakes('sanitary', 2),
    tipKeys: tips('sanitary', 2),
    checklistItemKeys: checklist('sanitary', 3),
    relatedVideoIds: [],
    contentComplete: false,
  },
  {
    id: 'electrical',
    order: 13,
    nameKey: 'stages.electrical.name',
    categoryKey: 'stages.categories.installations',
    objectiveKey: 'guides.electrical.objective',
    difficulty: 5,
    requiresProfessional: 'required',
    tools: {
      essentialKeys: ['tools.wireStripper', 'tools.multimeter', 'tools.screwdriverSet'],
      optionalKeys: ['tools.fishTape'],
      safetyKeys: ['safety.insulatedGloves', 'safety.glasses'],
    },
    prerequisiteStageIds: ['masonry'],
    stepKeys: steps('electrical', 9),
    commonMistakeKeys: mistakes('electrical', 4),
    tipKeys: tips('electrical', 3),
    checklistItemKeys: checklist('electrical', 6),
    relatedVideoIds: ['electrical-basics'],
    contentComplete: true,
  },
  {
    id: 'network',
    order: 14,
    nameKey: 'stages.network.name',
    categoryKey: 'stages.categories.installations',
    objectiveKey: 'guides.network.objective',
    difficulty: 2,
    requiresProfessional: 'none',
    tools: {
      essentialKeys: ['tools.crimper', 'tools.cableTester'],
      optionalKeys: ['tools.fishTape'],
      safetyKeys: [],
    },
    prerequisiteStageIds: ['electrical'],
    stepKeys: steps('network', 4),
    commonMistakeKeys: mistakes('network', 2),
    tipKeys: tips('network', 2),
    checklistItemKeys: checklist('network', 3),
    relatedVideoIds: [],
    contentComplete: false,
  },
  {
    id: 'telephony',
    order: 15,
    nameKey: 'stages.telephony.name',
    categoryKey: 'stages.categories.installations',
    objectiveKey: 'guides.telephony.objective',
    difficulty: 1,
    requiresProfessional: 'none',
    tools: { essentialKeys: ['tools.crimper'], optionalKeys: [], safetyKeys: [] },
    prerequisiteStageIds: ['electrical'],
    stepKeys: steps('telephony', 3),
    commonMistakeKeys: mistakes('telephony', 1),
    tipKeys: tips('telephony', 1),
    checklistItemKeys: checklist('telephony', 2),
    relatedVideoIds: [],
    contentComplete: false,
  },
  {
    id: 'hvac',
    order: 16,
    nameKey: 'stages.hvac.name',
    categoryKey: 'stages.categories.installations',
    objectiveKey: 'guides.hvac.objective',
    difficulty: 3,
    requiresProfessional: 'recommended',
    tools: {
      essentialKeys: ['tools.drill', 'tools.level'],
      optionalKeys: [],
      safetyKeys: ['safety.glasses'],
    },
    prerequisiteStageIds: ['electrical'],
    stepKeys: steps('hvac', 3),
    commonMistakeKeys: mistakes('hvac', 2),
    tipKeys: tips('hvac', 2),
    checklistItemKeys: checklist('hvac', 3),
    relatedVideoIds: [],
    contentComplete: false,
  },
  {
    id: 'solar-power',
    order: 17,
    nameKey: 'stages.solarPower.name',
    categoryKey: 'stages.categories.installations',
    objectiveKey: 'guides.solarPower.objective',
    difficulty: 5,
    requiresProfessional: 'required',
    tools: {
      essentialKeys: ['tools.drill', 'tools.multimeter'],
      optionalKeys: [],
      safetyKeys: ['safety.harness', 'safety.insulatedGloves'],
    },
    prerequisiteStageIds: ['electrical'],
    stepKeys: steps('solar-power', 4),
    commonMistakeKeys: mistakes('solar-power', 2),
    tipKeys: tips('solar-power', 2),
    checklistItemKeys: checklist('solar-power', 3),
    relatedVideoIds: [],
    contentComplete: false,
  },
  {
    id: 'solar-heating',
    order: 18,
    nameKey: 'stages.solarHeating.name',
    categoryKey: 'stages.categories.installations',
    objectiveKey: 'guides.solarHeating.objective',
    difficulty: 4,
    requiresProfessional: 'recommended',
    tools: {
      essentialKeys: ['tools.pipeCutter', 'tools.level'],
      optionalKeys: [],
      safetyKeys: ['safety.harness'],
    },
    prerequisiteStageIds: ['hydraulic'],
    stepKeys: steps('solar-heating', 4),
    commonMistakeKeys: mistakes('solar-heating', 2),
    tipKeys: tips('solar-heating', 1),
    checklistItemKeys: checklist('solar-heating', 3),
    relatedVideoIds: [],
    contentComplete: false,
  },
  {
    id: 'flooring',
    order: 19,
    nameKey: 'stages.flooring.name',
    categoryKey: 'stages.categories.finishing',
    objectiveKey: 'guides.flooring.objective',
    difficulty: 3,
    requiresProfessional: 'none',
    tools: {
      essentialKeys: [
        'tools.notchedTrowel',
        'tools.rubberMallet',
        'tools.spacers',
        'tools.tileCutter',
      ],
      optionalKeys: ['tools.laserLevel'],
      safetyKeys: ['safety.knee', 'safety.glasses'],
    },
    prerequisiteStageIds: ['waterproofing'],
    stepKeys: steps('flooring', 10),
    commonMistakeKeys: mistakes('flooring', 4),
    tipKeys: tips('flooring', 3),
    checklistItemKeys: checklist('flooring', 6),
    relatedVideoIds: ['flooring-basics'],
    contentComplete: true,
  },
  {
    id: 'wall-covering',
    order: 20,
    nameKey: 'stages.wallCovering.name',
    categoryKey: 'stages.categories.finishing',
    objectiveKey: 'guides.wallCovering.objective',
    difficulty: 3,
    requiresProfessional: 'none',
    tools: {
      essentialKeys: ['tools.notchedTrowel', 'tools.level'],
      optionalKeys: [],
      safetyKeys: ['safety.glasses'],
    },
    prerequisiteStageIds: ['masonry'],
    stepKeys: steps('wall-covering', 4),
    commonMistakeKeys: mistakes('wall-covering', 2),
    tipKeys: tips('wall-covering', 1),
    checklistItemKeys: checklist('wall-covering', 3),
    relatedVideoIds: [],
    contentComplete: false,
  },
  {
    id: 'drywall',
    order: 21,
    nameKey: 'stages.drywall.name',
    categoryKey: 'stages.categories.finishing',
    objectiveKey: 'guides.drywall.objective',
    difficulty: 3,
    requiresProfessional: 'none',
    tools: {
      essentialKeys: ['tools.screwGun', 'tools.level', 'tools.utilityKnife'],
      optionalKeys: [],
      safetyKeys: ['safety.mask', 'safety.glasses'],
    },
    prerequisiteStageIds: ['electrical'],
    stepKeys: steps('drywall', 4),
    commonMistakeKeys: mistakes('drywall', 2),
    tipKeys: tips('drywall', 2),
    checklistItemKeys: checklist('drywall', 3),
    relatedVideoIds: [],
    contentComplete: false,
  },
  {
    id: 'painting',
    order: 22,
    nameKey: 'stages.painting.name',
    categoryKey: 'stages.categories.finishing',
    objectiveKey: 'guides.painting.objective',
    difficulty: 2,
    requiresProfessional: 'none',
    tools: {
      essentialKeys: [
        'tools.paintRoller',
        'tools.paintBrush',
        'tools.paintTray',
        'tools.sandpaper',
      ],
      optionalKeys: ['tools.paintSprayer'],
      safetyKeys: ['safety.mask', 'safety.glasses', 'safety.dropCloth'],
    },
    prerequisiteStageIds: ['wall-covering'],
    stepKeys: steps('painting', 10),
    commonMistakeKeys: mistakes('painting', 4),
    tipKeys: tips('painting', 3),
    checklistItemKeys: checklist('painting', 5),
    relatedVideoIds: ['painting-basics'],
    contentComplete: true,
  },
  {
    id: 'doors',
    order: 23,
    nameKey: 'stages.doors.name',
    categoryKey: 'stages.categories.finishing',
    objectiveKey: 'guides.doors.objective',
    difficulty: 2,
    requiresProfessional: 'none',
    tools: {
      essentialKeys: ['tools.level', 'tools.screwGun', 'tools.chisel'],
      optionalKeys: [],
      safetyKeys: ['safety.gloves'],
    },
    prerequisiteStageIds: ['painting'],
    stepKeys: steps('doors', 4),
    commonMistakeKeys: mistakes('doors', 2),
    tipKeys: tips('doors', 1),
    checklistItemKeys: checklist('doors', 3),
    relatedVideoIds: [],
    contentComplete: false,
  },
  {
    id: 'deck',
    order: 24,
    nameKey: 'stages.deck.name',
    categoryKey: 'stages.categories.outdoor',
    objectiveKey: 'guides.deck.objective',
    difficulty: 3,
    requiresProfessional: 'recommended',
    tools: {
      essentialKeys: [
        'tools.circularSaw',
        'tools.screwGun',
        'tools.level',
        'tools.stringLine',
      ],
      optionalKeys: ['tools.miterSaw'],
      safetyKeys: ['safety.glasses', 'safety.gloves'],
    },
    prerequisiteStageIds: ['site-work'],
    stepKeys: steps('deck', 8),
    commonMistakeKeys: mistakes('deck', 3),
    tipKeys: tips('deck', 2),
    checklistItemKeys: checklist('deck', 5),
    relatedVideoIds: ['deck-basics'],
    contentComplete: true,
  },
  {
    id: 'pool',
    order: 25,
    nameKey: 'stages.pool.name',
    categoryKey: 'stages.categories.outdoor',
    objectiveKey: 'guides.pool.objective',
    difficulty: 5,
    requiresProfessional: 'required',
    tools: {
      essentialKeys: ['tools.level', 'tools.trowel'],
      optionalKeys: ['tools.craneOrHoist'],
      safetyKeys: ['safety.harness', 'safety.glasses'],
    },
    prerequisiteStageIds: ['structure'],
    stepKeys: steps('pool', 5),
    commonMistakeKeys: mistakes('pool', 3),
    tipKeys: tips('pool', 1),
    checklistItemKeys: checklist('pool', 4),
    relatedVideoIds: [],
    contentComplete: false,
  },
  {
    id: 'jacuzzi',
    order: 26,
    nameKey: 'stages.jacuzzi.name',
    categoryKey: 'stages.categories.outdoor',
    objectiveKey: 'guides.jacuzzi.objective',
    difficulty: 4,
    requiresProfessional: 'required',
    tools: {
      essentialKeys: ['tools.level', 'tools.wrenchSet'],
      optionalKeys: [],
      safetyKeys: ['safety.insulatedGloves'],
    },
    prerequisiteStageIds: ['electrical', 'hydraulic'],
    stepKeys: steps('jacuzzi', 4),
    commonMistakeKeys: mistakes('jacuzzi', 2),
    tipKeys: tips('jacuzzi', 1),
    checklistItemKeys: checklist('jacuzzi', 3),
    relatedVideoIds: [],
    contentComplete: false,
  },
  {
    id: 'outdoor-area',
    order: 27,
    nameKey: 'stages.outdoorArea.name',
    categoryKey: 'stages.categories.outdoor',
    objectiveKey: 'guides.outdoorArea.objective',
    difficulty: 2,
    requiresProfessional: 'none',
    tools: {
      essentialKeys: ['tools.shovel', 'tools.level'],
      optionalKeys: [],
      safetyKeys: ['safety.gloves'],
    },
    prerequisiteStageIds: ['site-work'],
    stepKeys: steps('outdoor-area', 3),
    commonMistakeKeys: mistakes('outdoor-area', 1),
    tipKeys: tips('outdoor-area', 1),
    checklistItemKeys: checklist('outdoor-area', 2),
    relatedVideoIds: [],
    contentComplete: false,
  },
  {
    id: 'landscaping',
    order: 28,
    nameKey: 'stages.landscaping.name',
    categoryKey: 'stages.categories.outdoor',
    objectiveKey: 'guides.landscaping.objective',
    difficulty: 1,
    requiresProfessional: 'none',
    tools: {
      essentialKeys: ['tools.shovel', 'tools.rake'],
      optionalKeys: [],
      safetyKeys: ['safety.gloves'],
    },
    prerequisiteStageIds: ['outdoor-area'],
    stepKeys: steps('landscaping', 3),
    commonMistakeKeys: mistakes('landscaping', 1),
    tipKeys: tips('landscaping', 1),
    checklistItemKeys: checklist('landscaping', 2),
    relatedVideoIds: [],
    contentComplete: false,
  },
  {
    id: 'finishes',
    order: 29,
    nameKey: 'stages.finishes.name',
    categoryKey: 'stages.categories.finishing',
    objectiveKey: 'guides.finishes.objective',
    difficulty: 2,
    requiresProfessional: 'none',
    tools: {
      essentialKeys: ['tools.screwdriverSet', 'tools.caulkGun'],
      optionalKeys: [],
      safetyKeys: ['safety.gloves'],
    },
    prerequisiteStageIds: ['doors'],
    stepKeys: steps('finishes', 3),
    commonMistakeKeys: mistakes('finishes', 1),
    tipKeys: tips('finishes', 1),
    checklistItemKeys: checklist('finishes', 2),
    relatedVideoIds: [],
    contentComplete: false,
  },
  {
    id: 'final-inspection',
    order: 30,
    nameKey: 'stages.finalInspection.name',
    categoryKey: 'stages.categories.closing',
    objectiveKey: 'guides.finalInspection.objective',
    difficulty: 2,
    requiresProfessional: 'recommended',
    tools: {
      essentialKeys: ['tools.multimeter', 'tools.level', 'tools.notebook'],
      optionalKeys: [],
      safetyKeys: [],
    },
    prerequisiteStageIds: ['finishes'],
    stepKeys: steps('final-inspection', 5),
    commonMistakeKeys: mistakes('final-inspection', 2),
    tipKeys: tips('final-inspection', 2),
    checklistItemKeys: checklist('final-inspection', 6),
    relatedVideoIds: [],
    contentComplete: false,
  },
];

export function findStageDefinition(id: string): StageDefinition | undefined {
  return stageDefinitions.find((s) => s.id === id);
}

export function getOrderedStageDefinitions(): StageDefinition[] {
  return [...stageDefinitions].sort((a, b) => a.order - b.order);
}
